version: '3'
services: 
  api:
    container_name: adidas-product-review-services
    restart: always
    build: .
    ports:
       - "4001:4001"
    links:
      - database
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  database:
    container_name: database
    image: mongo
    ports:
      - "27017:27017"